
void LCD_init(void){
	
	SYSCTL_RCGCGPIO_R |= 0x03; 
	while ((SYSCTL_PRGPIO_R & 0x03) == 0){}

//PORTA
	GPIO_PORTA_DIR_R |=0xE0;
	GPIO_PORTA_DEN_R|=0xE0;
	GPIO_PORTA_AMSEL_R &= ~0xE0;	
	GPIO_PORTA_AFSEL_R &= ~ 0xFF;	
	GPIO_PORTA_PCTL_R &= ~ 0xFFFFFFFF;

//PORTB	
	GPIO_PORTB_DIR_R |=0xFF; 
	GPIO_PORTB_DEN_R |=0xFF;
	GPIO_PORTB_AMSEL_R &= ~0xFF;
	GPIO_PORTB_AFSEL_R &= ~0xFF;
	GPIO_PORTB_PCTL_R &= ~0xFFFFFFFF;
}